name: release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: crazy-max/ghaction-github-release@v1
        if: startsWith(github.ref, 'refs/tags/')
